### ISSUE TITLE
Readme should be more accurate

### ISSUE THREAD

**Issue by zhanzhenzhen** [browserify/browser-resolve#67]
1. It seems that options are not limited to the listed 5. "basedir", "extensions" in the resolve package can also be used, but I can't find that in readme.
2. There are some typo in the examples. For example,

``` javascript
var shims = {
    http: '/your/path/to/http.js'
};

var resolve = require('browser-resolve');
resolve('fs', { modules: shims }, function(err, path) {
    console.log(path);
});
```

I think it should be `resolve('http')`?

In the "Browser Field" section, why is there a "chromeapp" property?

**Comment by marionebl** [comment]
@zhanzhenzhen is this fixed with the latest changes to readme.md?
